name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: proyecto-final2-455303
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/proyecto-final2-455303/proyecto-grupo-4

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy proyecto-grupo-4 \
            --image gcr.io/proyecto-final2-455303/proyecto-grupo-4 \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
