name: Deploy Angular App to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 1) Configurar Node
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 2) Instalar dependencias
      - name: Instalar dependencias
        run: |
          cd proyecto_grupo_4
          npm i
          npm install -g @angular/cli
       # 3) Instalar Snyk y analizar el proyecto
      - name: Instalar y autenticar Snyk
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Escanear dependencias con Snyk
        run: |
          cd proyecto_grupo_4
          snyk test --severity-threshold=high

      - name: Generar reporte de seguridad Snyk
        run: |
          npm install -g snyk-to-html
          cd proyecto_grupo_4
          snyk test --json | snyk-to-html -o reporte-snyk.html
          
      - name: Subir reporte Snyk como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: reporte-snyk
          path: proyecto_grupo_4/reporte-snyk.html
      # 4) Ejecutar pruebas
      - name: Ejecutar pruebas
        run: |
          cd proyecto_grupo_4
          ng test --browsers=ChromeHeadless --watch=false --code-coverage

      # 5) Autenticarse con Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 6) Configurar gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: proyecto-final2-455303

      # 7) Construir y subir la imagen Docker
      - name: Build and push Docker image
        run: |
          cd proyecto_grupo_4
          gcloud builds submit --tag gcr.io/proyecto-final2-455303/proyecto-grupo-4 .

      # 8) Desplegar a Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy proyecto-grupo-4 \
            --image gcr.io/proyecto-final2-455303/proyecto-grupo-4 \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated


